steps:

- id: 'get secrets'
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: [ '-c', 'gcloud secrets versions access latest --secret=slack-token > /workspace/token.txt' ]

- id: 'tf init'
  name: hashicorp/terraform:0.12.24
  entrypoint: terraform
  dir: terraform
  args: ['init', '-backend-config=bucket=${PROJECT_ID}-tfstate']

- id: 'tf plan'
  name: hashicorp/terraform:0.12.24
  entrypoint: sh
  dir: terraform
  args: ['-c', 'terraform plan  -var project_id=${PROJECT_ID} -var slack_verification_token=$(cat /workspace/token.txt)']
