steps:
- id: 'branch name'
  name: 'alpine'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      echo "***********************"
      echo "$BRANCH_NAME"
      echo "***********************"

- id: 'tf init'
  name: 'hashicorp/terraform:0.12.24'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      cd terraform
      echo ""
      echo "*************** TERRAFORM INIT ******************"
      echo "******* At branch: $BRANCH_NAME ********"
      echo "*************************************************"
      terraform init "-backend-config=bucket=$PROJECT_ID-tfstate" || exit 1
      cd ../


- id: 'tf plan'
  name: 'hashicorp/terraform:0.12.24'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      cd terraform
      echo ""
      echo "*************** TERRAFORM INIT ******************"
      echo "******* At branch: $BRANCH_NAME ********"
      echo "*************************************************"
      terraform plan -var "project_id=${PROJECT_ID}"  || exit 1
      cd ../


- id: 'tf apply'
  name: 'hashicorp/terraform:0.12.24'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      cd terraform
      echo ""
      echo "*************** TERRAFORM APPLY *****************"
      echo "******* At branch: $BRANCH_NAME ********"
      echo "*************************************************"
      terraform apply -var "project_id=$PROJECT_ID" -var "slack_verification_token=$$SLACK_VERIFICATION_TOKEN" -auto-approve
  secretEnv: ['SLACK_VERIFICATION_TOKEN']


secrets:
- kmsKeyName: projects/test-slack-chuck/locations/global/keyRings/slackchuck-token-keyring/cryptoKeys/slack-token
  secretEnv:
    SLACK_VERIFICATION_TOKEN: 'CiQAKjK5e4QFu9vs/rN89eEuj54jjitAis8s3YKeOKilf/XXd1ASQQCGuvbQoENOS3xjDCA0NVt1p1wiPI/pewEO4elLwboglnbbFbuMYvwXbpkGboHT1nYJxQEIrM28RbjAMkaZGQSk'
