on: [push, pull_request]
name: CI
jobs:
  statics:
    name: Static checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install python
        uses: actions/setup-python@v1
      - name: Install Go
        uses: actions/setup-go@v2-beta
        with:
          go-version: 1.13
      - name: Install go-lint
        run: |
          go get -u golang.org/x/lint/golint
          export PATH=$PATH:$(go list -f {{.Target}} golang.org/x/lint/golint)
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Terraform Init
        run: cd terraform && terraform init
      - name: Run pre-commit
        uses: pre-commit/action@v1.0.1

  unittests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install python
        uses: actions/setup-python@v1
      - name: Install Go
        uses: actions/setup-go@v2-beta
        with:
          go-version: 1.13
      - name: Get dependencies
        run: "go get -v -t -d ./..."
      - name: Run unit tests
        run: go test ./test -v

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install python
        uses: actions/setup-python@v1
      - name: Install Go
        uses: actions/setup-go@v2-beta
        with:
          go-version: 1.13
      - name: Get dependencies
        run: "go get -v -t -d ./..."
      - name: Build
        run: go build -v -o start ./cmd
